### ISSUE TITLE
app ディレクトリーの使用を検討する

### ISSUE THREAD

**Issue by piro0919** [yanachuwan9sm/own-fm#39]
**Is your feature request related to a problem? Please describe.**
Next.js の v13 では page container components の格納場所が pages と app の 2 箇所に対応している。
おそらく今後は app のほうに寄せられていくのではないかと予想しているのだが、既存の機能が一部動かなかったりするので、どちらを選択するかは微妙なラインである。

**Describe the solution you'd like**
将来を見据え app ディレクトリに移行する。

**Describe alternatives you've considered**
appディレクトリでやってみる。

**Additional context**
[App Directory Roadmap](https://beta.nextjs.org/docs/app-directory-roadmap)

**Comment by yanachuwan9sm** [comment]
(memo)

## App Directory

- `app` ディレクトリ内のコンポーネントはデフォルトで `Server Component(RFC) `として扱う
-  Client Component として扱う場合には "use client" をファイルの先頭で明示的に宣言する必要あり。
(Client Component  -> サーバー上でプリレンダリングした HTMLとJSONをキャッシュ、その結果はクライアントに送信され、Hydrationを行う。従来の挙動のもの。)
- Server Component で async/await を使用して非同期で(Promise<JSX.Element> を返す)データを取得することができる。

参考 : https://beta.nextjs.org/docs/rendering/server-and-client-components


## Server Components と Clinet Components どちらを使うべきか。

要件 | Server Components | Client Component 
-- | -- | --
[データフェッチ](https://beta.nextjs.org/docs/data-fetching/fetching)を使う  | ✅ | ⚠️
バックエンドリソースへのアクセス（直接） | ✅ | ❌
機密情報（アクセストークン、APIキーなど）をサーバーに保管する。 | ✅ | ❌
大きな依存関係をサーバーに残す / クライアントサイドのJavaScriptを削減する | ✅ | ❌
インタラクティブ機能とイベントリスナー（onClick()、onChange()など）を追加する。 | ❌ | ✅
ステートとライフサイクルエフェクトの使用(useState(),useReducer(),useEffect(), etc.) | ❌ | ✅
ブラウザ専用のAPIを使用する | ❌ | ✅
ステート、エフェクト、ブラウザ専用APIに依存するカスタムフックの使用 | ❌ | ✅
Reactクラスのコンポーネントを使用する | ❌ | ✅

参考 : https://beta.nextjs.org/docs/rendering/server-and-client-components#when-to-use-server-vs-client-components

**Comment by yanachuwan9sm** [comment]
検討した結果、app directly でやってみる方針にしたので
このissueはcloseしますmm
