### ISSUE TITLE
環境構築(ESLint,Prettier,Husky)の導入を行う

### ISSUE THREAD

**Issue by yanachuwan9sm** [yanachuwan9sm/own-fm#4]
**Is your feature request related to a problem? Please describe.**

以下の理由から、環境構築にあたりリンターとフォーマッターを導入する。

- チーム内(今回の場合は一人だが)における、コードのスタイルの一貫性を保つため。(コードの品質を保つ)
- コードRv時に、重要な箇所(設計・ロジック部分)に集中するため（コードのスタイルの指摘に時間を割くのを防ぐ）

**Describe the solution you'd like**

`eslint,Prettier`パッケージのインストール、
及び `client/` 配下に、 `.eslintrc.json` ファイルを作成する。
(ファイル数を少しでも少なくするため、Prettierの設定は package.json で行う)

**Additional context**

- `ESLint,Prettier`パッケージのインストール (cnaで作成したため、デフォルトで ESLint はインストール済)
- `client/` 配下に、 `.eslintrc.json` ファイルを作成 (cnaで作成したため、デフォルトで .eslintrc.json 作成済)
-   Prettierの設定を `package.json` に記述
- `npm script` に format・lint・fix それぞれのコマンドを追加
- `Husky`および `lint-staged`パッケージのインストール

**Comment by piro0919** [comment]
@yanachuwan9sm 

Issue の粒度が少し粗いので、以下の粒度で分割したほうが良いかなーと思いますが、いかがでしょうか。 👀 

- Prettier の導入
- Husky の導入

ESLint については Create Next App を導入した段階で導入済みとなるため、一旦保留で良いかなと。

**Comment by yanachuwan9sm** [comment]
@piro0919 

>Issue の粒度が少し粗いので、以下の粒度で分割したほうが良いかなーと思いますが、いかがでしょうか。

Discord においても、ご意見頂き有難う御座います！

Issue の粒度が荒い、または目的が曖昧な場合は、
PR の改修範囲が広くなってしまい、レビューに時間がかかってしまう等の
デメリットに繋がることが多いとの事承知しました。
issue の目的を明確にするためにも、細かく切るようにしていくので、
このissueはpiroさんのご教示いただいたように以下の粒度で分割致します！

- Prettier の導入
- Husky の導入

>ESLint については Create Next App を導入した段階で導入済みとなるため、一旦保留で良いかなと。

こちら ESLint の設定に関して疑問点等ありますので、別途issue作成致します。

また方針が決まり不要なissueとなったため、クローズ致します🙏
