### ISSUE TITLE
npm パッケージのアップデートを自動化する

### ISSUE THREAD

**Issue by piro0919** [yanachuwan9sm/own-fm#7]
**Is your feature request related to a problem? Please describe.**
npm パッケージのアップデートを手動で行う場合、見落としが発生する可能性がある。
一定のバージョンアップについては自動的にアップデートを行うようにし、開発コストを減らしたい。

**Describe the solution you'd like**
- Renovate を導入する

**Describe alternatives you've considered**
- Dependabot を導入する

**Comment by yanachuwan9sm** [comment]
ref #28 
こちらにて Renovateの設定まで完了しているためこのissueはクローズします🙏
