### ISSUE TITLE
markdownに含まれている画像を next/image に対応させる

### ISSUE THREAD

**Issue by yanachuwan9sm** [yanachuwan9sm/own-fm#94]
**Is your feature request related to a problem? Please describe.**

markdownt中に含まれている `![Dog](/images/dog.png) `のような埋め込まれた画像を、
HTMLに出力する際に、`next/image` に変換する。また、プレースホルダーにも対応させる。

**Describe the solution you'd like**

- [この記事](https://zenn.dev/elpnt/articles/c17727e9d254ef00ea60)を参考に、imgタグをnext/imageに変換する rehype Plugin を実装する

- 画像は Contentful内で管理する。

- 動的な画像の場合、[blurDataURL](https://nextjs.org/docs/api-reference/next/image#blurdataurl)プロパティを指定する必要があるため、[公式Docs](https://plaiceholder.co/plugins/next)の通り、 `plaiceholder @plaiceholder/next`を導入する。

**Comment by piro0919** [comment]
@yanachuwan9sm 

> 動的な画像の場合、[blurDataURL](https://nextjs.org/docs/api-reference/next/image#blurdataurl)プロパティを指定する必要があるため、[公式Docs](https://plaiceholder.co/plugins/next)の通り、 plaiceholder @plaiceholder/nextを導入する。

上記のドキュメントですが、Next のバージョンが古いやつなのでこのままだと動かないかもです。
一応共有までー。
